<a href="https://colab.research.google.com/github/KunalAyush1/MachineLearningBasicProjects/blob/main/LogisticRegressionfromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import expit


In [2]:
class Logistic_Regression():
  def __init__(self,learning_rate, no_of_iterations):
    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations

  def fit(self,X,Y):
    self.m,self.n = X.shape
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    for i in range(self.no_of_iterations):
      self.update_weights()


  def update_weights(self):
      Y_hat = expit(np.dot(self.X, self.w) + self.b)

      dw = 1/self.m * np.dot(self.X.T,(Y_hat - self.Y))
      db = 1/self.m * np.sum(Y_hat - self.Y)

      self.w = self.w - self.learning_rate * dw
      self.b = self.b - self.learning_rate * db




  def predict(self, X):
        X = np.array(X)
        Y_hat = expit(np.dot(X, self.w) + self.b)
        Y_pred = np.where(Y_hat >= 0.5, 1, 0)
        return Y_pred

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [4]:
data = pd.read_csv('/content/heart.csv')

In [5]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [6]:
data.shape

(1025, 14)

In [7]:
X = data.drop('target', axis=1).values

In [8]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [9]:
Y = data.iloc[:,13].values

In [10]:
print(Y)

[0 0 0 ... 0 1 0]


In [11]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state = 2)

In [13]:
print(X_train.shape)

(820, 13)


In [14]:
model = Logistic_Regression(learning_rate = 0.02 , no_of_iterations = 1000)

In [15]:
model.fit(X_train,Y_train)

In [16]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train , X_train_prediction)

In [17]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test , X_test_prediction)

In [19]:
print(training_data_accuracy)

0.6060975609756097


In [20]:
print(test_data_accuracy)

0.6487804878048781
